# Generated by Django 5.1 on 2026-04-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='url',
        ),
        migrations.AddField(
            model_name='work',
            name='file',
            field=models.FileField(default=1, upload_to='works/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF')], max_length=10),
        ),
    ]
