# Generated by Django 5.1 on 2026-04-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_remove_work_url_work_file_alter_work_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='tab',
            field=models.CharField(choices=[('Sadə-Təmir', 'Sadə-Təmir'), ('Skandinav-Təmir', 'Skandinav-Təmir'), ('Modern-Təmir', 'Modern-Təmir'), ('Loft-Təmir', 'Loft-Təmir'), ('Klassik-Təmir', 'Klassik-Təmir'), ('Qaba-Tikinti', 'Qaba-Tikinti')], max_length=50),
        ),
    ]
